name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3: ['^10.4']
        php: ['7.2', '7.3', '7.4']

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: typo3
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP Version
        run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          php -v

      - name: Update Composer
        run: |
          sudo composer self-update
          composer --version

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-typo3-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: |
          composer require typo3/minimal:${{ matrix.typo3 }}
          git checkout composer.json

      - name: Unit tests
        run: .Build/bin/phpunit --colors -c Tests/Build/UnitTests.xml

      - name: Functional tests
        run: |
          export typo3DatabaseName="typo3";
          export typo3DatabaseHost="127.0.0.1";
          export typo3DatabaseUsername="root";
          export typo3DatabasePassword="";
          .Build/bin/phpunit --colors -c Tests/Build/FunctionalTests.xml
